language: node_js
node_js:
  - "8"
before_script:
  - npm install
script:
  - npm run generate:gh-pages
deploy:
 provider: pages
 skip_cleanup: true
 local_dir: dist
 github_token: $GITHUB_TOKEN
 on:
  branch: develop
